# Generated by Django 6.0.4 on 2026-06-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_add_team_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='weekly_recap_opt_in',
            field=models.BooleanField(default=True, help_text='Per-user preference for the weekly recap email. Opt-out model: default True. When False, this user receives no weekly recap even for teams they own/manage that have it enabled.'),
        ),
    ]
