# Generated by Django 6.0.4 on 2026-06-06 10:47
#
# Three-step pattern for adding a unique field with a callable default
# (https://docs.djangoproject.com/en/6.0/howto/writing-migrations/
#  #migrations-that-add-unique-fields):
#   1. add the column WITHOUT the unique constraint (callable default
#      gives every existing row a value, but Django would otherwise apply
#      the default only once);
#   2. backfill a freshly generated, unique token per existing row;
#   3. add the unique constraint now that every row holds a distinct value.

import customuser.models
from django.db import migrations, models


def backfill_calendar_tokens(apps, schema_editor):
    CustomUser = apps.get_model("customuser", "CustomUser")
    for user in CustomUser.objects.all().iterator():
        user.calendar_token = customuser.models.generate_calendar_token()
        user.save(update_fields=["calendar_token"])


def noop_reverse(apps, schema_editor):
    # Nothing to undo: the field itself is removed by the AddField reversal.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_customuser_weekly_recap_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='calendar_token',
            field=models.CharField(
                db_index=True,
                default=customuser.models.generate_calendar_token,
                help_text=(
                    "Unguessable token embedded in the user's personal iCal "
                    "(.ics) subscription URL. The token IS the authentication "
                    "for that (otherwise anonymous) feed. Rotate it to revoke "
                    "an old URL."
                ),
                max_length=64,
            ),
        ),
        migrations.RunPython(backfill_calendar_tokens, noop_reverse),
        migrations.AlterField(
            model_name='customuser',
            name='calendar_token',
            field=models.CharField(
                db_index=True,
                default=customuser.models.generate_calendar_token,
                help_text=(
                    "Unguessable token embedded in the user's personal iCal "
                    "(.ics) subscription URL. The token IS the authentication "
                    "for that (otherwise anonymous) feed. Rotate it to revoke "
                    "an old URL."
                ),
                max_length=64,
                unique=True,
            ),
        ),
    ]
