# Generated by Django 6.0.4 on 2026-06-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_weeklyrecaplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='digest_email',
            field=models.BooleanField(default=False, help_text="When True, suppress immediate notification emails and instead send a single daily digest of the day's notifications. Opt-in (default False)."),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_digest_at',
            field=models.DateTimeField(blank=True, help_text='When the last notification digest was sent to this user.', null=True),
        ),
    ]
