# Generated by Django 6.0.4 on 2026-06-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0008_customuser_digest_email_customuser_last_digest_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="magic_link_nonce",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Single-use nonce for the current passwordless magic-login link. Set when a link is requested, baked into the signed token, and cleared (consumed) on exchange — so a link works at most once and a new request invalidates the previous one. NULL = no link pending.",
                max_length=32,
                null=True,
            ),
        ),
    ]
