# Generated by Django 6.0.6 on 2026-07-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0013_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bypass_granted_at',
            field=models.DateTimeField(blank=True, help_text='Audit only: when the access was first granted.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bypass_note',
            field=models.CharField(blank=True, help_text='Audit only: why this account was offered access.', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_bypass',
            field=models.BooleanField(default=False, help_text='When True, grants every paid feature without a subscription (offered access): the team quota becomes unlimited. Distinct from is_staff, which grants no business entitlement.'),
        ),
    ]
