# Generated by Django 6.0.4 on 2026-06-05 21:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0005_alter_event_refer_program'),
        ('member', '0005_alter_member_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotis', to='event.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotis', to='member.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'member'], name='roti_roti_event_i_9f2997_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'member'), name='uniq_roti_event_member')],
            },
        ),
    ]
