# Generated by Django 6.0.4 on 2026-06-05 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
        ('team', '0008_add_join_request_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='level.level'),
        ),
    ]
