# Generated by Django 6.0.4 on 2026-06-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_team_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.TextField(blank=True, default='', help_text="Small base64 data-URL for the team logo (e.g. 'data:image/png;base64,...'). Stored inline in the DB; no file storage."),
        ),
        migrations.AddField(
            model_name='team',
            name='roti_enabled',
            field=models.BooleanField(default=False, help_text="If True, athletes can submit a per-session difficulty rating (ROTI, 1..5) for the team's events."),
        ),
    ]
