# Generated by Django 6.0.4 on 2026-06-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_team_logo_team_roti_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='athlete_can_read_notes',
        ),
        migrations.AddField(
            model_name='team',
            name='weekly_recap_enabled',
            field=models.BooleanField(default=False, help_text='If True, this team is included in the weekly recap email sent to its owner and managers. Default False (opt-in per team).'),
        ),
    ]
