# Generated by Django 6.0.4 on 2026-06-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_remove_team_athlete_can_read_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='timezone',
            field=models.CharField(default='Europe/Brussels', help_text="IANA timezone name (e.g. 'Europe/Brussels'). Used to decide, in the team's local time, whether a session is over for per-aspect athlete visibility (vis_distance/vis_goal/vis_rounds).", max_length=64),
        ),
        migrations.AddField(
            model_name='team',
            name='vis_distance',
            field=models.CharField(choices=[('always', 'Always'), ('after', 'After the session'), ('never', 'Never')], default='always', help_text="Default visibility of a session's total distance to athletes. Inherited by new events; overridable per event.", max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='vis_goal',
            field=models.CharField(choices=[('always', 'Always'), ('after', 'After the session'), ('never', 'Never')], default='always', help_text="Default visibility of a session's goal to athletes. Inherited by new events; overridable per event.", max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='vis_rounds',
            field=models.CharField(choices=[('always', 'Always'), ('after', 'After the session'), ('never', 'Never')], default='always', help_text="Default visibility of a session's rounds (and their exercises) to athletes. Inherited by new events; overridable per event.", max_length=10),
        ),
    ]
