# Generated by Django 6.0.4 on 2026-06-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_team_timezone_team_vis_distance_team_vis_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='notify_athlete_on_visible_note',
            field=models.BooleanField(default=True, help_text='When True, an athlete with a linked user account is notified when a note shared with them (visible_to_athlete=True) is added.'),
        ),
        migrations.AddField(
            model_name='team',
            name='notify_coaches_on_note',
            field=models.BooleanField(default=True, help_text="When True, the team owner and managers (except the author) are notified each time a note is added on one of the team's athletes."),
        ),
    ]
