# Generated by Django 6.0.4 on 2026-06-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_team_notify_athlete_on_visible_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='topic_creation',
            field=models.CharField(choices=[('owner', 'Owner only'), ('coaches', 'Owner and coaches'), ('members', 'Everyone (incl. athletes)')], default='coaches', help_text='Who may create messaging topics in this team. owner = team owner only; coaches = owner and managers; members = owner, managers, and active athlete members.', max_length=10),
        ),
    ]
