# Generated by Django 6.0.4 on 2026-06-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_team_topic_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rsvp_enabled',
            field=models.BooleanField(default=False, help_text="If True, athletes can declare their availability (RSVP: going / maybe / not going) for the team's events."),
        ),
    ]
