# Generated by Django 6.0.4 on 2026-06-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_team_rsvp_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='public_sharing_enabled',
            field=models.BooleanField(default=False, help_text='Allow individual sessions of this team to be shared via a public read-only link.'),
        ),
        migrations.AddField(
            model_name='team',
            name='public_show_distance',
            field=models.BooleanField(default=True, help_text="Show a shared session's total distance on its public link."),
        ),
        migrations.AddField(
            model_name='team',
            name='public_show_goal',
            field=models.BooleanField(default=False, help_text="Show a shared session's goal on its public link."),
        ),
        migrations.AddField(
            model_name='team',
            name='public_show_rounds',
            field=models.BooleanField(default=True, help_text="Show a shared session's rounds & exercises on its public link."),
        ),
    ]
