# Generated by Django 6.0.4 on 2026-06-06 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_team_public_sharing_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='default_pool',
            field=models.CharField(blank=True, default='', help_text="Default venue/pool for this team's sessions (used by the season-plan generator).", max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='season_end',
            field=models.DateField(blank=True, help_text='Default season end date, pre-fills the plan generator.', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='season_start',
            field=models.DateField(blank=True, help_text='Default season start date, pre-fills the plan generator.', null=True),
        ),
        migrations.CreateModel(
            name='TrainingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (Python convention: Monday=0 … Sunday=6).')),
                ('hour_start', models.TimeField(help_text='Slot start time (local team time).')),
                ('hour_end', models.TimeField(help_text='Slot end time; must be after hour_start.')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_slots', to='team.team')),
            ],
            options={
                'ordering': ['weekday', 'hour_start'],
            },
        ),
    ]
