# Generated by Django 6.0.4 on 2026-06-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
        ('team', '0017_team_default_pool_team_season_end_team_season_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='default_place',
            field=models.ForeignKey(blank=True, help_text="Optional managed default venue (Lieu). When set, the canonical free-text 'default_pool' is synced to the place's name so the AI plan generator keeps reading default_pool unchanged.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='place.place'),
        ),
    ]
