# Generated by Django 6.0.4 on 2026-06-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipment_uniq_equipment_team_name_and_more'),
        ('team', '0018_team_default_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='equipment',
            field=models.ManyToManyField(blank=True, help_text='Equipment from the global catalog this team is allowed to use. Sessions can only reference equipment in this enabled set.', related_name='teams', to='equipment.equipment'),
        ),
    ]
