# Generated by Django 6.0.4 on 2026-06-07 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_remove_place_uniq_place_team_name_place_sport_and_more'),
        ('team', '0019_team_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='places',
            field=models.ManyToManyField(blank=True, help_text='Venues (Lieux) from the global sport-scoped pool this team uses. A place can belong to several teams in parallel.', related_name='teams', to='place.place'),
        ),
        migrations.AlterField(
            model_name='team',
            name='default_place',
            field=models.ForeignKey(blank=True, help_text="The team's default venue (Lieu), one of its linked places. When set, the canonical free-text 'default_pool' is synced to the place's name so the AI plan generator keeps reading it unchanged.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='place.place'),
        ),
    ]
