# Generated by Django 6.0.4 on 2026-06-08 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_remove_place_team'),
        ('team', '0020_team_places_alter_team_default_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingslot',
            name='place',
            field=models.ForeignKey(blank=True, help_text="Optional venue for this weekly slot. Defaults (in the UI) to the team's default_place; feeds the season-plan generator per day.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='place.place'),
        ),
    ]
