# Generated by Django 6.0.4 on 2026-06-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0021_trainingslot_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='chat_mode',
        ),
    ]
