# Generated by Django 6.0.4 on 2026-06-08 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_seed_default_sport'),
        ('team', '0022_remove_team_chat_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_sports', to='sport.sport')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_sports', to='team.team')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='+', through='team.TeamSport', to='sport.sport'),
        ),
        migrations.AddConstraint(
            model_name='teamsport',
            constraint=models.UniqueConstraint(fields=('team', 'sport'), name='uniq_team_sport'),
        ),
        migrations.AddConstraint(
            model_name='teamsport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('team',), name='uniq_default_sport_per_team'),
        ),
    ]
