# Generated by Django 6.0.4 on 2026-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_seed_default_sport'),
        ('team', '0024_backfill_team_sports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='sport',
        ),
        migrations.AlterField(
            model_name='team',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='teams', through='team.TeamSport', to='sport.sport'),
        ),
    ]
