# Generated by Django 6.0.4 on 2026-06-08 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_seed_default_sport'),
        ('team', '0025_remove_team_sport_alter_team_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingslot',
            name='sport',
            field=models.ForeignKey(blank=True, help_text="Sport of this weekly slot (one of the team's sports). The season-plan generator stamps each generated session's sport from its slot; defaults to the team's default sport.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sport.sport'),
        ),
    ]
