# Generated by Django 6.0.4 on 2026-06-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0027_backfill_trainingslot_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsport',
            name='training_type',
            field=models.CharField(blank=True, choices=[('structured', 'Structured (rounds & exercises)'), ('freeform', 'Free text')], default=None, help_text="Team override of the sport's default training type. Null = inherit Sport.default_training_type.", max_length=20, null=True),
        ),
    ]
