# Generated by Django 6.0.4 on 2026-06-07 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('sport', '0006_seed_default_sport'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipment',
            name='uniq_equipment_team_name',
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name_en',
            field=models.CharField(help_text="Display name of the equipment (e.g. 'Pull-buoy').", max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name_es',
            field=models.CharField(help_text="Display name of the equipment (e.g. 'Pull-buoy').", max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name_fr',
            field=models.CharField(help_text="Display name of the equipment (e.g. 'Pull-buoy').", max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name_it',
            field=models.CharField(help_text="Display name of the equipment (e.g. 'Pull-buoy').", max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name_nl',
            field=models.CharField(help_text="Display name of the equipment (e.g. 'Pull-buoy').", max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sport',
            field=models.ForeignKey(blank=True, help_text='Sport this equipment belongs to (e.g. Natation).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='sport.sport'),
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='team',
        ),
    ]
