# Generated by Django 6.0.4 on 2026-06-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_remove_program_events'),
        ('team', '0028_teamsport_training_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['team', 'is_active'], name='program_pro_team_id_c81d58_idx'),
        ),
    ]
