# Generated by Django 6.0.4 on 2026-06-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_seed_default_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='default_training_type',
            field=models.CharField(choices=[('structured', 'Structured (rounds & exercises)'), ('freeform', 'Free text')], default='structured', help_text='Default training-content type for events of this sport (overridable per team and per event).', max_length=20),
        ),
    ]
