# Generated by Django 6.0.4 on 2026-06-06 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0005_alter_member_email'),
        ('team', '0016_team_public_sharing_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Discipline / test name, e.g. '100m freestyle' or 'Cooper test'.", max_length=120, verbose_name='label')),
                ('value', models.DecimalField(decimal_places=3, help_text='Numeric result, interpreted by unit (seconds for time, meters for distance, etc.).', max_digits=10)),
                ('unit', models.CharField(choices=[('s', 'Seconds'), ('m', 'Meters'), ('reps', 'Repetitions'), ('kg', 'Kilograms'), ('pts', 'Points')], default='s', max_length=10)),
                ('recorded_on', models.DateField(help_text='Date the performance was achieved.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_performances', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='member.member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='team.team')),
            ],
            options={
                'ordering': ['-recorded_on', '-id'],
                'indexes': [models.Index(fields=['member', 'label'], name='performance_member__575e2b_idx'), models.Index(fields=['team', 'recorded_on'], name='performance_team_id_8d9a2c_idx')],
            },
        ),
    ]
