# Generated by Django 6.0.4 on 2026-06-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_refer_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vis_distance',
            field=models.CharField(choices=[('always', 'Always'), ('after', 'After the session'), ('never', 'Never')], default='always', help_text="Visibility of this session's total distance to athletes.", max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='vis_goal',
            field=models.CharField(choices=[('always', 'Always'), ('after', 'After the session'), ('never', 'Never')], default='always', help_text="Visibility of this session's goal to athletes.", max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='vis_rounds',
            field=models.CharField(choices=[('always', 'Always'), ('after', 'After the session'), ('never', 'Never')], default='always', help_text="Visibility of this session's rounds (and exercises) to athletes.", max_length=10),
        ),
    ]
