# Generated by Django 6.0.4 on 2026-06-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_vis_distance_event_vis_goal_event_vis_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='equipment',
            field=models.TextField(blank=True, default='', help_text='Material/gear athletes should bring. Always visible to athletes.', verbose_name='equipment'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Where the session takes place (venue, pool, track, address). Always visible to athletes.', max_length=255, verbose_name='location'),
        ),
    ]
