# Generated by Django 6.0.4 on 2026-06-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_equipment_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this session is currently shared via its public link.'),
        ),
        migrations.AddField(
            model_name='event',
            name='public_token',
            field=models.CharField(blank=True, default=None, help_text='Unguessable token in the public share URL. Null = never shared. The token authenticates the otherwise-anonymous public view.', max_length=64, null=True, unique=True),
        ),
    ]
