# Generated by Django 6.0.4 on 2026-06-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_is_public_event_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='goal',
            field=models.TextField(blank=True, null=True, verbose_name='goal'),
        ),
    ]
