# Generated by Django 6.0.4 on 2026-06-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_event_goal'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, help_text="Optional managed venue (Lieu). When set, the canonical free-text 'location' is synced to the place's name. Deleting the place clears this FK but leaves 'location' intact.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='place.place'),
        ),
    ]
