# Generated by Django 6.0.4 on 2026-06-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('event', '0010_event_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='equipment_items',
            field=models.ManyToManyField(blank=True, help_text="Managed equipment (Matériel) used by this session. When set, the canonical free-text 'equipment' is synced to the joined item names.", related_name='events', to='equipment.equipment'),
        ),
    ]
