# Generated by Django 6.0.4 on 2026-06-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_seed_global_equipment'),
        ('event', '0011_event_equipment_items'),
        ('member', '0005_alter_member_email'),
        ('place', '0005_remove_place_team'),
        ('program', '0008_remove_program_events'),
        ('round', '0009_add_mmss_validator'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['refer_program', 'date'], name='event_program_date_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='event_date_idx'),
        ),
    ]
