# Generated by Django 6.0.4 on 2026-06-08 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_event_program_date_idx_event_event_date_idx'),
        ('sport', '0006_seed_default_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.ForeignKey(blank=True, help_text="The sport this session is for (one of the team's sports). Scopes the modalities/exercises offered and the AI generation; defaults to the team's default sport.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sport.sport'),
        ),
    ]
