# Generated by Django 6.0.4 on 2026-06-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_backfill_event_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='training_richtext',
            field=models.TextField(blank=True, default='', help_text='Free-text training content (sanitized HTML) when training_type=freeform.'),
        ),
        migrations.AddField(
            model_name='event',
            name='training_type',
            field=models.CharField(choices=[('structured', 'Structured (rounds & exercises)'), ('freeform', 'Free text')], default='structured', help_text="This event's active training-content type. Seeded at creation from the team-sport / sport cascade; editable by the coach.", max_length=20),
        ),
    ]
