# Generated by Django 6.0.4 on 2026-06-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_event_training_richtext_event_training_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='debrief',
            field=models.TextField(blank=True, default='', verbose_name='debrief'),
        ),
    ]
