# Generated by Django 6.0.4 on 2026-06-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_event_debrief'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ai_athlete_brief',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='ai_brief_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
