# Generated by Django 6.0.4 on 2026-06-10 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_event_ai_athlete_brief_event_ai_brief_generated_at'),
        ('round', '0010_round_author'),
        ('sport', '0007_sport_default_training_type'),
        ('team', '0028_teamsport_training_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('goal', models.TextField(blank=True, default='')),
                ('total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rounds', models.ManyToManyField(blank=True, related_name='+', to='round.round')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sport.sport')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_templates', to='team.team')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['team', 'name'], name='event_event_team_id_babd22_idx')],
            },
        ),
    ]
