# Generated by Django 6.0.6 on 2026-07-10 16:18

from django.db import migrations, models


def seed_total_target_from_total(apps, schema_editor):
    """Existing sessions carried their volume in `total`; adopt it as the
    coach's target so nothing loses its objective on the split."""
    Event = apps.get_model("event", "Event")
    Event.objects.filter(total__gt=0).update(total_target=models.F("total"))


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_eventtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(
            seed_total_target_from_total,
            migrations.RunPython.noop,
        ),
    ]
