# Generated by Django 6.0.4 on 2026-06-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='visible_to_athlete',
            field=models.BooleanField(default=False, help_text='If True, the concerned athlete can read this note (when it is also active). Default False — notes are coach-only unless explicitly shared.'),
        ),
    ]
