# Generated by Django 6.0.4 on 2026-06-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0002_note_visible_to_athlete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(help_text="Rich HTML content (sanitized via nh3 on save)."),
        ),
    ]
