# Generated by Django 6.0.4 on 2026-06-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_repair_mojibake_referentials'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['language', 'order'], name='exercise_ex_languag_e73672_idx'),
        ),
    ]
