# Generated by Django 6.0.4 on 2026-06-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0017_team_default_pool_team_season_end_team_season_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name of the venue (e.g. 'Piscine olympique').", max_length=255, verbose_name='name')),
                ('address', models.CharField(blank=True, default='', help_text='Optional postal address / directions for the venue.', max_length=500, verbose_name='address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='team.team')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('team', 'name'), name='uniq_place_team_name')],
            },
        ),
    ]
