# Generated by Django 6.0.4 on 2026-06-07 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_backfill_places_from_locations'),
        ('sport', '0006_seed_default_sport'),
        ('team', '0019_team_equipment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='place',
            name='uniq_place_team_name',
        ),
        migrations.AddField(
            model_name='place',
            name='sport',
            field=models.ForeignKey(blank=True, help_text='Sport this venue belongs to (e.g. Natation).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='sport.sport'),
        ),
        migrations.AlterField(
            model_name='place',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='team.team'),
        ),
    ]
