# Generated by Django 6.0.4 on 2026-06-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_migrate_places_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='team',
        ),
    ]
