# Generated by Django 6.0.4 on 2026-06-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_remove_place_team'),
        ('sport', '0006_seed_default_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='sports',
            field=models.ManyToManyField(blank=True, help_text='Sports this venue serves.', related_name='+', to='sport.sport'),
        ),
    ]
