# Generated by Django 6.0.4 on 2026-06-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_backfill_place_sports'),
        ('sport', '0006_seed_default_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='sport',
        ),
        migrations.AlterField(
            model_name='place',
            name='sports',
            field=models.ManyToManyField(blank=True, help_text='Sports this venue serves.', related_name='places', to='sport.sport'),
        ),
    ]
