# Generated by Django 6.0.4 on 2026-06-06 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0013_team_notify_athlete_on_visible_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audience', models.CharField(choices=[('team', 'Whole team'), ('coaches', 'Coaches only')], default='team', help_text='team = visible to all team members; coaches = visible only to the owner and managers (staff channel).', max_length=10)),
                ('allow_athlete_replies', models.BooleanField(default=True, help_text='Only meaningful when audience=team. When True, athlete members may post messages; coaches can always post.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Bumped on each new message for activity-based ordering.')),
                ('author', models.ForeignKey(blank=True, help_text='The coach who created the topic. SET_NULL on user deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics_authored', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='team.team')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Rich HTML content (sanitized via bleach on save).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, help_text='Author of the message. SET_NULL on user deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_messages_authored', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.topic')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['team', 'audience', '-updated_at'], name='topic_team_audience_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['topic', 'created_at'], name='message_topic_created_idx'),
        ),
    ]
