# Generated by Django 6.0.4 on 2026-06-08 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Set when the message is edited after creation.', null=True),
        ),
        migrations.CreateModel(
            name='TopicRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(help_text='Moment the user last read this topic.')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='messaging.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'topic'), name='uniq_topicread_user_topic')],
            },
        ),
    ]
