# Generated by Django 6.0.4 on 2026-06-06 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0016_team_public_sharing_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, default='', help_text="Snapshot of the actor's username/display at the time. Survives actor deletion or anonymization (when the FK is SET_NULL).", max_length=150)),
                ('action', models.CharField(choices=[('member_anonymized', 'Member anonymized'), ('member_removed', 'Member removed from team'), ('account_deleted', 'Account deleted'), ('session_shared', 'Session shared publicly'), ('session_unshared', 'Session sharing disabled'), ('attachment_deleted', 'Attachment deleted'), ('team_config_updated', 'Team configuration updated')], help_text='Stable code identifying the audited action.', max_length=50)),
                ('target_repr', models.CharField(blank=True, default='', help_text='Human-readable description of the target.', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Small structured extra context (no unnecessary PII).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who performed the action. NULL = system/anonymous.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Team the action is scoped to (used for read scoping). NULL = not team-scoped, e.g. an account self-delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='team.team')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'created_at'], name='audit_team_created_idx')],
            },
        ),
    ]
