# Generated by Django 6.0.6 on 2026-07-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(choices=[('member_anonymized', 'Member anonymized'), ('member_removed', 'Member removed from team'), ('account_deleted', 'Account deleted'), ('session_shared', 'Session shared publicly'), ('session_unshared', 'Session sharing disabled'), ('attachment_deleted', 'Attachment deleted'), ('team_config_updated', 'Team configuration updated'), ('subscription_bypass_granted', 'Offered access granted'), ('subscription_bypass_revoked', 'Offered access revoked')], help_text='Stable code identifying the audited action.', max_length=50),
        ),
    ]
