# Generated by Django 6.0.4 on 2026-06-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('note_for_coach', 'Note added on an athlete'), ('note_for_athlete', 'A note was shared with you'), ('message_new_topic', 'A new topic was created in your team'), ('message_new_reply', 'A new message was posted in a topic')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='type',
            field=models.CharField(choices=[('note_for_coach', 'Note added on an athlete'), ('note_for_athlete', 'A note was shared with you'), ('message_new_topic', 'A new topic was created in your team'), ('message_new_reply', 'A new message was posted in a topic')], max_length=40),
        ),
    ]
