# Generated by Django 6.0.4 on 2026-06-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('note_for_coach', 'Note added on an athlete'), ('note_for_athlete', 'A note was shared with you'), ('message_new_topic', 'A new topic was created in your team'), ('message_new_reply', 'A new message was posted in a topic'), ('performance_logged', 'A performance was logged for you'), ('pb_beaten', 'You beat a personal best'), ('plan_generated', 'A new training plan was scheduled'), ('session_reminder', 'You have a session tomorrow')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='type',
            field=models.CharField(choices=[('note_for_coach', 'Note added on an athlete'), ('note_for_athlete', 'A note was shared with you'), ('message_new_topic', 'A new topic was created in your team'), ('message_new_reply', 'A new message was posted in a topic'), ('performance_logged', 'A performance was logged for you'), ('pb_beaten', 'You beat a personal best'), ('plan_generated', 'A new training plan was scheduled'), ('session_reminder', 'You have a session tomorrow')], max_length=40),
        ),
    ]
