# Generated by Django 6.0.6 on 2026-06-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='push',
            field=models.BooleanField(default=True),
        ),
    ]
