# Generated by Django 6.0.4 on 2026-06-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_seed_unknown_status_and_align_colors'),
        ('event', '0015_event_training_richtext_event_training_type'),
        ('member', '0005_alter_member_email'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status', 'event'], name='attendance__status__a9794c_idx'),
        ),
    ]
