# Generated by Django 6.0.4 on 2026-06-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiusage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusage',
            name='endpoint',
            field=models.CharField(choices=[('ping', 'Ping'), ('plan', 'Generate plan'), ('training', 'Generate training'), ('training_freeform', 'Generate free-text training'), ('review', 'Review training block')], max_length=20),
        ),
    ]
